### ISSUE TITLE
[BUG] - Cannot set 0 value on Pixelate filter

### ISSUE THREAD

**Issue by JDDoesDev** [FiniteSingularity/obs-composite-blur#17] opened 2023-08-31 01:22 UTC
**Describe the bug**
When trying to set up pixelate filter on a source and using Exeldro's Move Value transition alongside this plugin I am unable to set the value of the idle filter to 0 px which causes a slight blur on the source.  Setting the value to 0 would allow for the filter to be active and use the move value transition to animate the blur on and off.

**To Reproduce**
1. Add a move transition filter (assuming use of Exeldro's plugin)
2. Attempt to set the value in the move transition settings to 0.
3. Notice that you are unable to set to anything below 0.

**Expected behavior**
I expect that I should be able to set the value to 0 so that I can use the transition to adjust the value between 0 and a positive number.

**Screenshots**

**Environment**
 - OS/Version: [e.g. Windows 11]
 - OBS Version: [e.g. 29.1.2]
 - OBS Composite Blur Plugin Version: [e.g. 0.0.5-alpha]
 - Blur Algorithm/Type: [e.g. Pixelate]

**Comment by FiniteSingularity** [comment] 2023-08-31 01:53
Thank you for opening the issue.  I can see how it would be a little confusing, however this is actually working as intended, as a pixel at size 1, is just the original pixel (so in terms of pixelization, 1 pixel is zero blur).  We could allow the value to go to zero, as there is a check to see if the value is 1 or smaller, it just passes through the original frame.  Is there any particular use case where having it go to zero is needed?  Would it be less confusing to allow the slider to go to zero?

**Comment by JDDoesDev** [comment] 2023-08-31 02:05
I didn't have anyone in chat answering when I was attempting to use the transition, but in studio mode when enabling and disabling at 1.00 it seemed that there was a bit of a blurring, although minor.  Let me see if I can find it in the VOD.

**Comment by FiniteSingularity** [comment] 2023-08-31 02:09
Its definitely possible. It may have something to do with the float error that comes in, where a value of 1.0 is actually 1.0000001, which is greater than 1, so it isn't passing through the source.  If that is the case, I can set an epsilon value to catch float rounding errors.

**Comment by JDDoesDev** [comment] 2023-08-31 02:10
https://www.twitch.tv/videos/1912841249 at 4:02:20 roughly.  

There is some minor blurring, but after reviewing the VOD it is almost imperceptible.  I'll let you take a look and decide if it's enough to put in a fix for, however I'm willing to close this as invalid after checking the VOD.

**Comment by FiniteSingularity** [comment] 2023-09-11 10:22
I am going to close this one for now, as "works as expected."  I am still considering allowing a "dummy" zero value for Pixelate and Dual Kawase, but that would come in the next feature release.

**Closed as completed by FiniteSingularity** 2023-09-11 10:22 UTC
Labels: bug

**Comment by FiniteSingularity** [comment] 2023-09-16 15:18
@all-contributors please add @JDDoesDev for bug
